[package]
name = "mdbook-snippets"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["cargo"] }
mdbook-core.workspace = true
mdbook-preprocessor.workspace = true
regex.workspace = true
serde_json.workspace = true
