[workspace]
resolver = "2"
members = [
  "crates/breez-sdk/cli",
  "crates/breez-sdk/common",
  "crates/breez-sdk/core", 
  "crates/macros",
  "crates/spark",
  "crates/spark-itest",
  "crates/spark-wallet", 
  "crates/xtask",
  "examples/spark-cli", 
]

[workspace.package]
version = "0.1.0"

[workspace.lints.clippy]
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
struct_field_names = "allow"
arithmetic_side_effects = "warn"

[workspace.dependencies]
aes = "0.8.4"
anyhow = "1.0.98"
async-trait = "0.1.88"
base64 = "0.22.1"
bech32 = "0.11.0"
bip39 = "2.2.0"
bitcoin = { version = "0.32.6", features = ["serde"] }
breez-sdk-common = { path = "crates/breez-sdk/common" }
breez-sdk-core = { path = "crates/breez-sdk/core" }
bytes = "1.10.1"
cargo_metadata = "0.18"
cbc = "0.1.2"
chrono = { version = "0.4.37", features = ["serde"] }
clap = "4.5.40"
dirs = "6.0.0"
dns-parser = "0.8.0"
dotenvy = "0.15.7"
ecies = { version = "0.2.7", default-features = false, features = ["pure"] }
enum_to_enum = "0.1.0"
figment = "0.10.19"
# frost-core = "2.1.0"
frost-core = { package = "frost-core-unofficial", version = "2.2.0" }
# frost-secp256k1-tr = "2.1.0"
frost-secp256k1-tr = { package = "frost-secp256k1-tr-unofficial", version = "2.2.0" }
futures = { version = "0.3", default-features = false }
graphql_client = { version = "0.14.0" }
hex = "0.4.3"
hickory-resolver = "0.25.2"
http = "1.3.1"
http-body = "1.0.1"
http-body-util = "0.1.3"
k256 = { version = "0.13.0", features = ["arithmetic", "schnorr", "ecdsa"] }
lightning = "0.1.3"
lightning-invoice = "0.33.1"
macros = { path = "crates/macros" }
maybe-sync = "0.1.1"
percent-encoding-rfc3986 = "0.1.3"
proc-macro2 = "1.0.97"
prost = "0.13.4"
prost-types = "0.13.4"
qrcode-rs = { version = "0.1", default-features = false }
quote = "1.0.40"
rand = "0.8"
rayon = "1.10"
reqwest = { version = "0.12.18", features = ["json"] }
rstest = "0.26.1"
rusqlite = { git = "https://github.com/Spxg/rusqlite", rev = "8e53118a3e1807dc9a9f59c5969fdff7e0416400", features = [
    "backup",
    "bundled",
] }
rusqlite_migration = { git = "https://github.com/breez/rusqlite_migration", branch = "spxg-rusqlite" }
rustls = { version = "0.23.28", default-features = false, features = ["ring"] }
rustyline = "16.0.0"
serde = "1.0.219"
serde_json = "1.0.140"
serde_with = "3.13.0"
shellwords = "1.1.0"
shlex = "1.3.0"
spark = { path = "crates/spark" }
spark-wallet = { path = "crates/spark-wallet" }
strum = "0.27.1"
strum_macros = "0.27.1"
syn = "2.0.105"
tempdir = "0.3.7"
test-log = { version = "0.2.18", default-features = false }
testcontainers = "0.24.0"
testcontainers-modules = "0.12.1"
testdir = "0.9.3"
thiserror = "2.0.12"
tokio = { version = "1.45.1", default-features = false }
tokio-postgres = "0.7.10"
tokio-test = "0.4.4"
tokio_with_wasm = { version = "0.8.7", features = ["macros", "rt", "sync", "time"] }
tonic = { version = "0.12.3", default-features = false }
tonic-build = { version = "0.12.3", features = ["prost"] }
tonic-web-wasm-client = "0.6"
tower-service = "0.3.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uniffi = "0.28.3"
uuid = { version = "1.17.0", features = ["v7", "v4"] }
wasm-bindgen-test = "0.3.33"
web-time = "1.1.0"
xshell = "0.2"