[workspace]
resolver = "2"

members = ["crates/spark", "crates/spark-wallet", "examples/spark-cli"]

[workspace.dependencies]
async-trait = "0.1.88"
base64 = "0.22.1"
bip32 = "0.5.3"
bip39 = "2.2.0"
bitcoin = "0.32.6"
chrono = { version = "0.4.37", features = ["serde"] }
clap = "4.5.40"
ecies = "0.2.0"
figment = "0.10.19"
# frost-core = "2.1.0"
frost-core = { package = "frost-core-unofficial", version = "2.2.0" }
# frost-secp256k1-tr = "2.1.0"
frost-secp256k1-tr = { package = "frost-secp256k1-tr-unofficial", version = "2.2.0" }
k256 = { version = "0.13.0", features = ["arithmetic", "schnorr", "ecdsa"] }
hex = "0.4.3"
prost = "0.13.4"
prost-types = "0.13.4"
reqwest = { version = "0.12.18", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
serde_with = "3.13.0"
spark = { path = "crates/spark" }
spark-macros = { path = "crates/spark-macros" }
spark-wallet = { path = "crates/spark-wallet" }
thiserror = "2.0.12"
tokio = { version = "1.45.1", default-features = false }
tonic = { version = "0.12.3", features = [
    "tls",
    "tls-webpki-roots",
    "prost",
    "channel",
] }
tonic-build = { version = "0.12.3", features = ["prost"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.17.0", features = ["v7"] }
lightning-invoice = "0.33.1"
futures = { version = "0.3", default-features = false }
rand = "0.8"