rust:
  directory: ../..
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkSpark
turboModule:
  cpp: cpp
  ts: src
noOverwrite:
  - "android/src/main/java/**/BreezSdkSparkReactNativePackage.kt"