[package]
name = "breez_sdk_spark_snippets"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1"
async-trait = "0.1.89"
breez-sdk-spark = { path = "../../../../crates/breez-sdk/core", features = ["postgres"] }
log = "0.4"
tokio = "1.42.0"
hex = "0.4.3"
sha256 = "1.6.0"
