[package]
name = "breez_sdk_spark_snippets"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
breez-sdk-spark.workspace = true
tokio.workspace = true
tracing.workspace = true
