[book]
language = "en"
src = "src"
title = "Breez SDK - Nodeless (Spark)"

[output.html]
theme = "theme"
additional-css = ["styles.css", "theme/pagetoc.css"]
additional-js = ["tabs.js", "theme/pagetoc.js"]
git-repository-url = "https://github.com/breez/spark-sdk"
edit-url-template = "https://github.com/breez/spark-sdk/edit/main/crates/breez-sdk/docs/{path}"
no-section-label = true

[output.html.fold]
enable = true

[output.html.print]
enable = false

[preprocessor.snippets]

[preprocessor.pagetoc]
command = "mdbook-pagetoc"
renderer = ["html"]

[preprocessor.variables.variables]
api_key_form_uri = "https://breez.technology/request-api-key/#contact-us-form-sdk"

# Basic llmstxt.org format output
[output.llms-txt]

# Detailed llmstxt.org format output with additional information
[output.llms-txt-full]
