[package]
name = "platform-utils"
version.workspace = true
edition = "2021"
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tokio_with_wasm.workspace = true

[lints]
workspace = true
