name: Publish Android Bindings
on:
  workflow_call:
    inputs:
      repository:
        description: 'SDK repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'Git commit, tag or branch reference'
        required: true
        type: string
      package-version:
        description: 'Version for the gradle library (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'Should publish to maven.'
        required: true
        type: boolean
        default: false
    secrets:
      BREEZ_MVN_USERNAME:
        description: 'Username for gradlew publish'
        required: true
      BREEZ_MVN_PASSWORD:
        description: 'Password for gradlew publish'
        required: true

jobs:
  build-language-bindings:
    name: Build language bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}
  
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download aarch64-linux-android
        uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-linux-android
          path: aarch64-linux-android

      - name: Build Kotlin language bindings
        working-directory: crates/breez-sdk/bindings
        run: |
          cargo install gobley-uniffi-bindgen --git https://github.com/breez/gobley --rev 72753910f54a157de2f84b78dc6f78415e28d4f2
          gobley-uniffi-bindgen --library -o ffi/kotlin --crate-configs breez_sdk_spark_bindings=./uniffi.toml --crate-configs breez_sdk_spark=../core/uniffi.toml ../../../aarch64-linux-android/libbreez_sdk_spark_bindings.so

      - name: Archive Kotlin language bindings
        uses: actions/upload-artifact@v4
        with:
          name: bindings-kotlin
          path: crates/breez-sdk/bindings/ffi/kotlin/main/kotlin/breez_sdk_spark

  build-package:
    name: Build package
    runs-on: ubuntu-latest
    needs: build-language-bindings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/download-artifact@v4
        with:
          name: bindings-android-jniLibs
          path: crates/breez-sdk/bindings/langs/android/lib/src/main/jniLibs

      - uses: actions/download-artifact@v4
        with:
          name: bindings-kotlin
          path: crates/breez-sdk/bindings/langs/android/lib/src/main/kotlin

      - name: Build Android project
        working-directory: crates/breez-sdk/bindings/langs/android
        env:
          ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.package-version || '0.0.1' }}
        run: ./gradlew assemble

      - name: Archive aar
        if: ${{ !inputs.publish }}
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ inputs.package-version || '0.0.2' }}
          path: crates/breez-sdk/bindings/langs/android/lib/build/outputs/aar/lib-release.aar
        
      - name: Publish artifacts
        if: ${{ inputs.publish }}
        working-directory: crates/breez-sdk/bindings/langs/android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
          BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
        run: |
          ./gradlew publish -PlibraryVersion=${{ inputs.package-version }} -PbreezReposiliteUsername="$BREEZ_MVN_USERNAME" -PbreezReposilitePassword="$BREEZ_MVN_PASSWORD"

      - name: Trigger Jitpack build
        if: ${{ inputs.publish }}
        shell: bash
        run: |
          # Jitpack only makes artifacts avaiable when someone requests them.
          # Here we trick Jitpack into thinking we're already requesting the newly built package
          # to make sure it is available right away for anyone that needs it later.
          # We're waiting for at most 60s before triggering the Jitpack build to give our Maven repo
          # some time to process the just uploaded files (the Jitpack build is dependent upon them being available).
          # If anything fails here, we'll still finish sucessfully as this is an optional optimization.
          timeout 60 bash -c 'while [[ "$(curl --output /dev/null --silent --head --write-out ''%{http_code}'' https://mvn.breez.technology/releases/breez_sdk_spark/bindings-android/${{ inputs.package-version }}/bindings-android-${{ inputs.package-version }}.pom)" != "200" ]]; do echo "Waiting for package to be published on mvn.breez.technology..." && sleep 5; done && echo "Package found."' || echo "Package not found." && true
          echo "Attempting to trigger Jitpack build..."
          curl -s -m 30 https://jitpack.io/api/builds/com.github.breez/spark-sdk/${{ inputs.package-version }} || true
          echo "Done"
